"""initial_schema

Revision ID: 3e7f689423eb
Revises:
Create Date: 2026-08-15 01:43:59.908902
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "3e7f689423eb"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("firebase_uid", sa.String(length=128), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=160), nullable=False),
        sa.Column("avatar_url", sa.Text(), nullable=True),
        sa.Column("experience_level", sa.String(length=64), nullable=True),
        sa.Column(
            "target_roles",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "primary_skills",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("preferred_language", sa.String(length=32), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("onboarding_completed", sa.Boolean(), nullable=False),
        sa.Column("last_active_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_firebase_uid"), "users", ["firebase_uid"], unique=True)
    op.create_table(
        "calendar_connections",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("provider_account_email", sa.String(length=320), nullable=True),
        sa.Column("encrypted_access_token", sa.Text(), nullable=True),
        sa.Column("encrypted_refresh_token", sa.Text(), nullable=True),
        sa.Column("token_expiry", sa.DateTime(timezone=True), nullable=True),
        sa.Column("scope", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "CONNECTED",
                "EXPIRED",
                "REVOKED",
                "ERROR",
                name="calendarconnectionstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("last_sync_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sync_cursor", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_calendar_connections_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calendar_connections")),
    )
    op.create_index(
        op.f("ix_calendar_connections_user_id"), "calendar_connections", ["user_id"], unique=False
    )
    op.create_index(
        "ix_calendar_connections_user_provider",
        "calendar_connections",
        ["user_id", "provider"],
        unique=False,
    )
    op.create_table(
        "notifications",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=180), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("action_label", sa.String(length=80), nullable=True),
        sa.Column("action_url", sa.Text(), nullable=True),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("scheduled_for", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_notifications_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    op.create_index(op.f("ix_notifications_user_id"), "notifications", ["user_id"], unique=False)
    op.create_index(
        "ix_notifications_user_read", "notifications", ["user_id", "read_at"], unique=False
    )
    op.create_table(
        "processing_jobs",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("phase", sa.String(length=64), nullable=True),
        sa.Column("idempotency_key", sa.String(length=128), nullable=True),
        sa.Column(
            "result",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("error_code", sa.String(length=96), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_processing_jobs_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_processing_jobs")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_processing_jobs_idempotency_key")),
    )
    op.create_index("ix_jobs_user_status", "processing_jobs", ["user_id", "status"], unique=False)
    op.create_index(op.f("ix_processing_jobs_status"), "processing_jobs", ["status"], unique=False)
    op.create_index(
        op.f("ix_processing_jobs_user_id"), "processing_jobs", ["user_id"], unique=False
    )
    op.create_table(
        "resumes",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("file_type", sa.String(length=80), nullable=False),
        sa.Column("storage_key", sa.String(length=512), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("raw_text", sa.Text(), nullable=True),
        sa.Column(
            "parsed_data",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("parse_status", sa.String(length=32), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_resumes_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_resumes")),
        sa.UniqueConstraint("storage_key", name=op.f("uq_resumes_storage_key")),
    )
    op.create_index(op.f("ix_resumes_content_hash"), "resumes", ["content_hash"], unique=False)
    op.create_index(op.f("ix_resumes_user_id"), "resumes", ["user_id"], unique=False)
    op.create_index("ix_resumes_user_primary", "resumes", ["user_id", "is_primary"], unique=False)
    op.create_table(
        "topic_performance",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("topic", sa.String(length=120), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("average_score", sa.Float(), nullable=False),
        sa.Column("best_score", sa.Float(), nullable=False),
        sa.Column("recent_score", sa.Float(), nullable=False),
        sa.Column("confidence_weight", sa.Float(), nullable=False),
        sa.Column("trend", sa.Float(), nullable=False),
        sa.Column("last_practiced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_topic_performance_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_topic_performance")),
    )
    op.create_index(
        op.f("ix_topic_performance_topic"), "topic_performance", ["topic"], unique=False
    )
    op.create_index(
        op.f("ix_topic_performance_user_id"), "topic_performance", ["user_id"], unique=False
    )
    op.create_index(
        "ix_topic_performance_user_topic", "topic_performance", ["user_id", "topic"], unique=True
    )
    op.create_table(
        "interviews",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("company_name", sa.String(length=180), nullable=False),
        sa.Column("role_title", sa.String(length=180), nullable=False),
        sa.Column("interview_type", sa.String(length=64), nullable=False),
        sa.Column("round_name", sa.String(length=120), nullable=True),
        sa.Column("round_number", sa.Integer(), nullable=True),
        sa.Column("total_rounds", sa.Integer(), nullable=True),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("meeting_type", sa.String(length=64), nullable=True),
        sa.Column("meeting_url", sa.Text(), nullable=True),
        sa.Column("location", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "DETECTED",
                "CONFIRMED",
                "UPCOMING",
                "COMPLETED",
                "CANCELLED",
                "REJECTED",
                "OFFER",
                name="interviewstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "source",
            sa.Enum(
                "MANUAL", "GOOGLE_CALENDAR", name="interviewsource", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("calendar_connection_id", sa.Uuid(), nullable=True),
        sa.Column("calendar_event_id", sa.String(length=512), nullable=True),
        sa.Column("job_description_id", sa.Uuid(), nullable=True),
        sa.Column("resume_id", sa.Uuid(), nullable=True),
        sa.Column("readiness_score", sa.Float(), nullable=True),
        sa.Column(
            "readiness_components",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("preparation_progress", sa.Float(), nullable=False),
        sa.Column("detection_confidence", sa.Float(), nullable=True),
        sa.Column(
            "detection_evidence",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["calendar_connection_id"],
            ["calendar_connections.id"],
            name=op.f("fk_interviews_calendar_connection_id_calendar_connections"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["resume_id"],
            ["resumes.id"],
            name=op.f("fk_interviews_resume_id_resumes"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_interviews_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_interviews")),
        sa.UniqueConstraint(
            "calendar_connection_id", "calendar_event_id", name="uq_interview_calendar_event"
        ),
    )
    op.create_index(
        op.f("ix_interviews_scheduled_at"), "interviews", ["scheduled_at"], unique=False
    )
    op.create_index(op.f("ix_interviews_status"), "interviews", ["status"], unique=False)
    op.create_index(op.f("ix_interviews_user_id"), "interviews", ["user_id"], unique=False)
    op.create_index(
        "ix_interviews_user_scheduled", "interviews", ["user_id", "scheduled_at"], unique=False
    )
    op.create_index("ix_interviews_user_status", "interviews", ["user_id", "status"], unique=False)
    op.create_table(
        "interview_rounds",
        sa.Column("interview_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["interview_id"],
            ["interviews.id"],
            name=op.f("fk_interview_rounds_interview_id_interviews"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_interview_rounds")),
        sa.UniqueConstraint("interview_id", "position", name="uq_round_position"),
    )
    op.create_index(
        op.f("ix_interview_rounds_interview_id"), "interview_rounds", ["interview_id"], unique=False
    )
    op.create_table(
        "job_descriptions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("interview_id", sa.Uuid(), nullable=True),
        sa.Column("raw_text", sa.Text(), nullable=False),
        sa.Column("company_name", sa.String(length=180), nullable=True),
        sa.Column("role_title", sa.String(length=180), nullable=True),
        sa.Column(
            "parsed_data",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "role_match_data",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("parse_status", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["interview_id"],
            ["interviews.id"],
            name=op.f("fk_job_descriptions_interview_id_interviews"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_job_descriptions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_descriptions")),
    )
    op.create_index(
        op.f("ix_job_descriptions_interview_id"), "job_descriptions", ["interview_id"], unique=False
    )
    op.create_index(
        op.f("ix_job_descriptions_user_id"), "job_descriptions", ["user_id"], unique=False
    )
    op.create_foreign_key(
        "fk_interviews_job_description_id_job_descriptions",
        "interviews",
        "job_descriptions",
        ["job_description_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_table(
        "mock_interview_sessions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("interview_id", sa.Uuid(), nullable=True),
        sa.Column("mode", sa.String(length=64), nullable=False),
        sa.Column("difficulty", sa.String(length=32), nullable=False),
        sa.Column("interviewer_style", sa.String(length=64), nullable=False),
        sa.Column("planned_duration", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "state",
            sa.Enum(
                "CREATED",
                "READY",
                "INTRODUCTION",
                "RESUME",
                "TECHNICAL",
                "BEHAVIORAL",
                "CANDIDATE_QUESTIONS",
                "WRAP_UP",
                "PROCESSING",
                "COMPLETED",
                name="sessionstate",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("current_section", sa.String(length=64), nullable=True),
        sa.Column("question_count", sa.Integer(), nullable=False),
        sa.Column("current_question_index", sa.Integer(), nullable=False),
        sa.Column("overall_score", sa.Float(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "CREATED",
                "ACTIVE",
                "PAUSED",
                "PROCESSING",
                "COMPLETED",
                "ABANDONED",
                name="sessionstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "compact_memory",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["interview_id"],
            ["interviews.id"],
            name=op.f("fk_mock_interview_sessions_interview_id_interviews"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_mock_interview_sessions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mock_interview_sessions")),
    )
    op.create_index(
        op.f("ix_mock_interview_sessions_interview_id"),
        "mock_interview_sessions",
        ["interview_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mock_interview_sessions_status"),
        "mock_interview_sessions",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mock_interview_sessions_user_id"),
        "mock_interview_sessions",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        "ix_sessions_user_status", "mock_interview_sessions", ["user_id", "status"], unique=False
    )
    op.create_table(
        "preparation_plans",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("interview_id", sa.Uuid(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("interview_date", sa.Date(), nullable=False),
        sa.Column("overall_progress", sa.Float(), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("prompt_version", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["interview_id"],
            ["interviews.id"],
            name=op.f("fk_preparation_plans_interview_id_interviews"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_preparation_plans_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_preparation_plans")),
    )
    op.create_index(
        op.f("ix_preparation_plans_interview_id"),
        "preparation_plans",
        ["interview_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_preparation_plans_user_id"), "preparation_plans", ["user_id"], unique=False
    )
    op.create_table(
        "ai_usage",
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("session_id", sa.Uuid(), nullable=True),
        sa.Column("agent", sa.String(length=80), nullable=False),
        sa.Column("prompt_version", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=180), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("error_code", sa.String(length=96), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["mock_interview_sessions.id"],
            name=op.f("fk_ai_usage_session_id_mock_interview_sessions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_ai_usage_user_id_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_usage")),
    )
    op.create_index(op.f("ix_ai_usage_session_id"), "ai_usage", ["session_id"], unique=False)
    op.create_index("ix_ai_usage_user_created", "ai_usage", ["user_id", "created_at"], unique=False)
    op.create_index(op.f("ix_ai_usage_user_id"), "ai_usage", ["user_id"], unique=False)
    op.create_table(
        "interview_reports",
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("overall_score", sa.Float(), nullable=False),
        sa.Column("technical_score", sa.Float(), nullable=False),
        sa.Column("communication_score", sa.Float(), nullable=False),
        sa.Column("structure_score", sa.Float(), nullable=False),
        sa.Column("clarity_score", sa.Float(), nullable=False),
        sa.Column("relevance_score", sa.Float(), nullable=False),
        sa.Column("depth_score", sa.Float(), nullable=False),
        sa.Column(
            "strengths",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "weaknesses",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "weak_topics",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "recommended_actions",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("prompt_version", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["mock_interview_sessions.id"],
            name=op.f("fk_interview_reports_session_id_mock_interview_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_interview_reports")),
    )
    op.create_index(
        op.f("ix_interview_reports_session_id"), "interview_reports", ["session_id"], unique=True
    )
    op.create_table(
        "preparation_tasks",
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=180), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("estimated_minutes", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "IN_PROGRESS",
                "COMPLETED",
                "SKIPPED",
                name="preparationtaskstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("resource_type", sa.String(length=64), nullable=True),
        sa.Column("resource_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["preparation_plans.id"],
            name=op.f("fk_preparation_tasks_plan_id_preparation_plans"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_preparation_tasks")),
    )
    op.create_index(op.f("ix_preparation_tasks_date"), "preparation_tasks", ["date"], unique=False)
    op.create_index(
        op.f("ix_preparation_tasks_plan_id"), "preparation_tasks", ["plan_id"], unique=False
    )
    op.create_table(
        "session_questions",
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("parent_question_id", sa.Uuid(), nullable=True),
        sa.Column("question_text", sa.Text(), nullable=False),
        sa.Column("question_type", sa.String(length=64), nullable=False),
        sa.Column("topic", sa.String(length=120), nullable=False),
        sa.Column("difficulty", sa.String(length=32), nullable=False),
        sa.Column("is_follow_up", sa.Boolean(), nullable=False),
        sa.Column("followup_depth", sa.Integer(), nullable=False),
        sa.Column("asked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_question_id"],
            ["session_questions.id"],
            name=op.f("fk_session_questions_parent_question_id_session_questions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["mock_interview_sessions.id"],
            name=op.f("fk_session_questions_session_id_mock_interview_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_session_questions")),
        sa.UniqueConstraint("session_id", "position", name="uq_question_position"),
    )
    op.create_index(
        op.f("ix_session_questions_session_id"), "session_questions", ["session_id"], unique=False
    )
    op.create_index(
        op.f("ix_session_questions_topic"), "session_questions", ["topic"], unique=False
    )
    op.create_table(
        "speech_metrics",
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("total_words", sa.Integer(), nullable=False),
        sa.Column("total_speaking_ms", sa.Integer(), nullable=False),
        sa.Column("average_wpm", sa.Float(), nullable=False),
        sa.Column("filler_count", sa.Integer(), nullable=False),
        sa.Column(
            "fillers",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("pause_count", sa.Integer(), nullable=False),
        sa.Column("long_pause_count", sa.Integer(), nullable=False),
        sa.Column("longest_pause_ms", sa.Integer(), nullable=False),
        sa.Column("average_pause_ms", sa.Float(), nullable=False),
        sa.Column("average_answer_ms", sa.Float(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["mock_interview_sessions.id"],
            name=op.f("fk_speech_metrics_session_id_mock_interview_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_speech_metrics")),
    )
    op.create_index(
        op.f("ix_speech_metrics_session_id"), "speech_metrics", ["session_id"], unique=True
    )
    op.create_table(
        "interview_answers",
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("question_id", sa.Uuid(), nullable=False),
        sa.Column("transcript", sa.Text(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("word_count", sa.Integer(), nullable=False),
        sa.Column(
            "pause_markers_ms",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["session_questions.id"],
            name=op.f("fk_interview_answers_question_id_session_questions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["mock_interview_sessions.id"],
            name=op.f("fk_interview_answers_session_id_mock_interview_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_interview_answers")),
    )
    op.create_index(
        op.f("ix_interview_answers_question_id"), "interview_answers", ["question_id"], unique=True
    )
    op.create_index(
        op.f("ix_interview_answers_session_id"), "interview_answers", ["session_id"], unique=False
    )
    op.create_table(
        "answer_evaluations",
        sa.Column("answer_id", sa.Uuid(), nullable=False),
        sa.Column("correctness", sa.Float(), nullable=False),
        sa.Column("completeness", sa.Float(), nullable=False),
        sa.Column("relevance", sa.Float(), nullable=False),
        sa.Column("depth", sa.Float(), nullable=False),
        sa.Column("structure", sa.Float(), nullable=False),
        sa.Column("clarity", sa.Float(), nullable=False),
        sa.Column(
            "strengths",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "missing_points",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "recommendations",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "improved_structure",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("prompt_version", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["answer_id"],
            ["interview_answers.id"],
            name=op.f("fk_answer_evaluations_answer_id_interview_answers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_answer_evaluations")),
    )
    op.create_index(
        op.f("ix_answer_evaluations_answer_id"), "answer_evaluations", ["answer_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_answer_evaluations_answer_id"), table_name="answer_evaluations")
    op.drop_table("answer_evaluations")
    op.drop_index(op.f("ix_interview_answers_session_id"), table_name="interview_answers")
    op.drop_index(op.f("ix_interview_answers_question_id"), table_name="interview_answers")
    op.drop_table("interview_answers")
    op.drop_index(op.f("ix_speech_metrics_session_id"), table_name="speech_metrics")
    op.drop_table("speech_metrics")
    op.drop_index(op.f("ix_session_questions_topic"), table_name="session_questions")
    op.drop_index(op.f("ix_session_questions_session_id"), table_name="session_questions")
    op.drop_table("session_questions")
    op.drop_index(op.f("ix_preparation_tasks_plan_id"), table_name="preparation_tasks")
    op.drop_index(op.f("ix_preparation_tasks_date"), table_name="preparation_tasks")
    op.drop_table("preparation_tasks")
    op.drop_index(op.f("ix_interview_reports_session_id"), table_name="interview_reports")
    op.drop_table("interview_reports")
    op.drop_index(op.f("ix_ai_usage_user_id"), table_name="ai_usage")
    op.drop_index("ix_ai_usage_user_created", table_name="ai_usage")
    op.drop_index(op.f("ix_ai_usage_session_id"), table_name="ai_usage")
    op.drop_table("ai_usage")
    op.drop_index(op.f("ix_preparation_plans_user_id"), table_name="preparation_plans")
    op.drop_index(op.f("ix_preparation_plans_interview_id"), table_name="preparation_plans")
    op.drop_table("preparation_plans")
    op.drop_index("ix_sessions_user_status", table_name="mock_interview_sessions")
    op.drop_index(op.f("ix_mock_interview_sessions_user_id"), table_name="mock_interview_sessions")
    op.drop_index(op.f("ix_mock_interview_sessions_status"), table_name="mock_interview_sessions")
    op.drop_index(
        op.f("ix_mock_interview_sessions_interview_id"), table_name="mock_interview_sessions"
    )
    op.drop_table("mock_interview_sessions")
    op.drop_constraint(
        "fk_interviews_job_description_id_job_descriptions",
        "interviews",
        type_="foreignkey",
    )
    op.drop_index(op.f("ix_job_descriptions_user_id"), table_name="job_descriptions")
    op.drop_index(op.f("ix_job_descriptions_interview_id"), table_name="job_descriptions")
    op.drop_table("job_descriptions")
    op.drop_index(op.f("ix_interview_rounds_interview_id"), table_name="interview_rounds")
    op.drop_table("interview_rounds")
    op.drop_index("ix_interviews_user_status", table_name="interviews")
    op.drop_index("ix_interviews_user_scheduled", table_name="interviews")
    op.drop_index(op.f("ix_interviews_user_id"), table_name="interviews")
    op.drop_index(op.f("ix_interviews_status"), table_name="interviews")
    op.drop_index(op.f("ix_interviews_scheduled_at"), table_name="interviews")
    op.drop_table("interviews")
    op.drop_index("ix_topic_performance_user_topic", table_name="topic_performance")
    op.drop_index(op.f("ix_topic_performance_user_id"), table_name="topic_performance")
    op.drop_index(op.f("ix_topic_performance_topic"), table_name="topic_performance")
    op.drop_table("topic_performance")
    op.drop_index("ix_resumes_user_primary", table_name="resumes")
    op.drop_index(op.f("ix_resumes_user_id"), table_name="resumes")
    op.drop_index(op.f("ix_resumes_content_hash"), table_name="resumes")
    op.drop_table("resumes")
    op.drop_index(op.f("ix_processing_jobs_user_id"), table_name="processing_jobs")
    op.drop_index(op.f("ix_processing_jobs_status"), table_name="processing_jobs")
    op.drop_index("ix_jobs_user_status", table_name="processing_jobs")
    op.drop_table("processing_jobs")
    op.drop_index("ix_notifications_user_read", table_name="notifications")
    op.drop_index(op.f("ix_notifications_user_id"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index("ix_calendar_connections_user_provider", table_name="calendar_connections")
    op.drop_index(op.f("ix_calendar_connections_user_id"), table_name="calendar_connections")
    op.drop_table("calendar_connections")
    op.drop_index(op.f("ix_users_firebase_uid"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
