from enum import StrEnum


class ErrorCode(StrEnum):
    INTERVIEW_NOT_FOUND = "INTERVIEW_NOT_FOUND"
    TASK_NOT_FOUND = "TASK_NOT_FOUND"
    SESSION_NOT_FOUND = "SESSION_NOT_FOUND"
    REPORT_NOT_FOUND = "REPORT_NOT_FOUND"
    ANALYSIS_NOT_FOUND = "ANALYSIS_NOT_FOUND"
    NOTIFICATION_NOT_FOUND = "NOTIFICATION_NOT_FOUND"
    HISTORY_SESSION_NOT_FOUND = "HISTORY_SESSION_NOT_FOUND"
    JOB_NOT_FOUND = "JOB_NOT_FOUND"
    RESUME_NOT_FOUND = "RESUME_NOT_FOUND"
    TICKET_INVALID = "TICKET_INVALID"
    UNSUPPORTED_FILE_TYPE = "UNSUPPORTED_FILE_TYPE"
    FILE_TOO_LARGE = "FILE_TOO_LARGE"
    UNAUTHENTICATED = "UNAUTHENTICATED"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    RATE_LIMITED = "RATE_LIMITED"
    REQUEST_FAILED = "REQUEST_FAILED"
